add server certificates
janmbaco/go-reverseproxy-ssl pull request #20
Opened 2020-09-16 22:01 UTC by janmbaco

Issue #19

2020-09-18 17:23 UTC, onixmtz requested changes
Lo único que rompería el comportamiento esperado parece lo del replacement de www. en **redirectToWWW** de _main.go_ (si fuera cierto)

2020-09-18 17:23 UTC, onixmtz commented on main.go
>  	if strings.Contains(hostname, "www") {
No sería mejor hacer esto sólo "si empieza por"? Con un host tipo holycowww.com no se comportaría mal?

2020-09-18 17:23 UTC, onixmtz commented on configs/certs/certificatedefs.go
> +	CaPem      string `json:"ca_pem"`
PEM son todos, no?

2020-09-18 17:23 UTC, onixmtz commented on configs/certs/certificatedefs.go
> +	if rootCAs == nil {
Esto no será mejor acabarlo metiendo como configurable o al menos que informe? Igual para desarrollo guay, pero en despliegues en los que cuenten con leer de la certstore (o mecanismo subyacente de la plataforma que fuere) de la máquina donde se despliega, si esto ni tan siquiera deja registro alguno, igual puede llegar ser complicado de debuggar

2020-09-19 07:46 UTC, janmbaco commented on configs/certs/certificatedefs.go
> +	if rootCAs == nil {
Debe obtener las autoridades certificadoras del sistema y añadir aquellas que sean de los certificados que se aportan. No entiendo muy bien tu comentario.

2020-09-19 08:18 UTC, janmbaco commented on configs/certs/certificatedefs.go
> +	CaPem      string `json:"ca_pem"`
En cierta manera es así, pero el certificado en sí distinguimos del público y privado, sin embargo, para la CA debe entregar el PEM "BEGIN CERTIFICATE\n ... \nEND CERTIFICATE", no la clave privada, por norma general estos archivos acaban teniendo la extensión .pem y mientras que los de la clave privada .key. Creo que poner que la CA ha de ser el pem es bastante claro.

2020-09-20 10:47 UTC, merged